### ISSUE TITLE
RAML 1.0 Parsing Error: Unable to cast object of type 'System.Object[]' to type 'System.Collections.Generic.IDictionary`2[System.String,System.Object]'.

### ISSUE THREAD

**Issue by dturkel** [mulesoft-labs/raml-dotnet-tools#209]
Similar to Issue #118 , I am receiving this error when on what is otherwise a valid set of RAML specifications when attempting to parse:

```
var parser = new RamlParser();
RamlDocument raml = await parser.LoadAsync(filePath)
```

This RAML is used (without issue) in an existing MS project.  Please let me know if any additional detail would be helpful.

[api.zip](https://github.com/mulesoft/raml-dotnet-tools/files/3442594/api.zip)

```
System.AggregateException was unhandled
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at MulesoftUtilities.MuleConfigurationFile.load() in C:\Users\dturkel\MSEATool1\MulesoftUtilities\MuleConfigurationFile.cs:line 73
       at MulesoftUtilities.MuleProject.load() in C:\Users\dturkel\MSEATool1\MulesoftUtilities\MuleProject.cs:line 162
       at MulesoftEnterpriseArchitectTool.MainForm.btnLoadCompare_Click(Object sender, EventArgs e) in C:\Users\dturkel\MSEATool1\MulesoftEnterpriseArchitectTool\MainForm.cs:line 561
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at MulesoftEnterpriseArchitectTool.Program.Main() in C:\Users\dturkel\MSEATool1\MulesoftEnterpriseArchitectTool\Program.cs:line 19
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2147467262
       Message=Unable to cast object of type 'System.Object[]' to type 'System.Collections.Generic.IDictionary`2[System.String,System.Object]'.
       Source=Raml.Parser
       StackTrace:
            at Raml.Parser.Builders.TypeBuilder.GetArray(IDictionary`2 dynamicRaml, String key)
            at Raml.Parser.Builders.TypeBuilder.SetPropertiesByType(KeyValuePair`2 pair, RamlType ramlType)
            at Raml.Parser.Builders.TypeBuilder.GetRamlType(KeyValuePair`2 type)
            at Raml.Parser.Builders.TypeBuilder.ParseProperties(IDictionary`2 dynamicRaml, ObjectType obj)
            at Raml.Parser.Builders.TypeBuilder.GetObject(IDictionary`2 dynamicRaml)
            at Raml.Parser.Builders.TypeBuilder.SetPropertiesByType(KeyValuePair`2 pair, RamlType ramlType)
            at Raml.Parser.Builders.TypeBuilder.GetRamlType(KeyValuePair`2 type)
            at Raml.Parser.Builders.TypeBuilder.AddTypes(RamlTypesOrderedDictionary ramlTypes_, IDictionary`2 dynamicRaml, String preffix_)
            at Raml.Parser.Builders.RamlBuilder.<Build>d__0.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at Raml.Parser.RamlParser.<LoadAsync>d__0.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at MulesoftUtilities.MuleConfigurationFile.<parseRamlDocument>d__11.MoveNext() in C:\Users\dturkel\MSEATool1\MulesoftUtilities\MuleConfigurationFile.cs:line 99
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at MulesoftUtilities.MuleConfigurationFile.<>c__DisplayClass10_0.<<load>b__0>d.MoveNext() in C:\Users\dturkel\MSEATool1\MulesoftUtilities\MuleConfigurationFile.cs:line 72
       InnerException: 
```

**Comment by woodp** [comment]
it parses without errors on the latest release
