### ISSUE TITLE
Visual Studio 2015 (Community) crashes while referencing RAML

### ISSUE THREAD

**Issue by bspruit** [mulesoft-labs/raml-dotnet-tools#99]
When attempting to reference a RAML file, Visual Studio 2015 (Community) freezes for a second and then crashes.
I installed the RAML plugin through the Visual Studio Extensions dialog:
![image](https://cloud.githubusercontent.com/assets/5729811/18679104/889edad8-7f5e-11e6-908c-5977201e7033.png)

I attempt to reference the RAML through the right click menu in the Solution Explorer:
![image](https://cloud.githubusercontent.com/assets/5729811/18679284/3bc9a2a0-7f5f-11e6-8a8f-bb61f8e6ef0c.png)

I tried both the direct RAML URL entry as the RAML Upload (after first downloading it):
![image](https://cloud.githubusercontent.com/assets/5729811/18679318/6c4a4f1a-7f5f-11e6-8d6c-cd84e6dbfb3b.png)
 
The RAML can be found here: https://anypoint.mulesoft.com/apiplatform/k-n-l-t-b/#/portals/organizations/ab1e6b05-49b4-4365-aa44-e320bd577d8b/apis/5101528/versions/97405/pages/148258.

The exception:
> Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at Microsoft.VisualStudio.PlatformUI.DisposableObject.ThrowIfDisposed()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.UnadviseHierarchyEvents()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.DocumentReleased(System.Object, System.EventArgs)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.FireDocumentReleased()
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.DocumentUnlocked(System.Object, System.EventArgs)
   at Microsoft.VisualStudio.Platform.WindowManagement.RdtLock.FireDocumentUnlocked()
   at Microsoft.VisualStudio.Platform.WindowManagement.RdtLock.UnlockDocument(Microsoft.VisualStudio.Platform.WindowManagement.RdtFlags)
   at Microsoft.VisualStudio.Platform.WindowManagement.RdtLock.DisposeNativeResources()
   at Microsoft.VisualStudio.PlatformUI.DisposableObject.Dispose(Boolean)
   at Microsoft.VisualStudio.PlatformUI.DisposableObject.Finalize()

There is some urgency to this issue, as it will define with which strategies we will market Mulesoft for the near future in regards to B2B interfacing.

Kind regards,
Björn T.J.M. Spruit

**Comment by woodp** [comment]
I'm sorry but I cannot reproduce the problem.

Tried downloading it and from URL (with this URL: https://anypoint.mulesoft.com/apiplatform/repository/v2/organizations/ab1e6b05-49b4-4365-aa44-e320bd577d8b/public/apis/5101528/versions/97405/files/root )

Tried in a class library, web api and in a console projects using visual studio 2015 community edition update 3.
All worked fine.

![2016-09-20_1540](https://cloud.githubusercontent.com/assets/675793/18684441/9400d304-7f4a-11e6-95e4-66d4db65578f.png)

**Comment by woodp** [comment]
Can you try in a different machine ?

**Comment by bspruit** [comment]
I can. I'll let you know if it turns out to be an environment (pc + installation) problem.
Thanks for the feedback!
